name: CI-Android-Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GUM_OPTIONS: '--enable-gumpp --with-devkits=gum'

jobs:
  android:
    strategy:
      matrix:
        id:
          - android-arm
          - android-arm64
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25
          add-to-path: false
      - name: Set ANDROID_NDK_ROOT
        run: echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
      - name: Build
        run: |
          ./configure --host=${{ matrix.id }} ${{ env.GUM_OPTIONS }}
          make
      - name: Upload Gum devkit
        uses: actions/upload-artifact@v4
        with:
          name: gum-devkit-${{ matrix.id }}
          path: build/gum/devkit/
